# Generated by Django 2.2 on 2019-06-06 08:56
from __future__ import unicode_literals
from django.db import migrations, models


def create_sentinel_plan(apps, schema_editor):
    Plan = apps.get_model('account', 'Plan')

    Plan(title='_sentinel').save()


def delete_sentinel_plan(apps, schema_editor):
    Plan = apps.get_model('account', 'Plan')

    Plan(title='_sentinel').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sentinel_plan, delete_sentinel_plan),
    ]
