# Generated by Django 2.2 on 2019-06-06 08:56
from __future__ import unicode_literals
from django.db import migrations, models


def create_sentinel_plan(apps, schema_editor):
    Plan = apps.get_model('account', 'Plan')

    Plan(title='_sentinel').save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='total_bandwidth',
            field=models.BigIntegerField(default=0, verbose_name='total_bandwidth'),
        ),
        migrations.RunPython(create_sentinel_plan),
    ]
