# Generated by Django 2.2 on 2019-06-09 06:25

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_add_sentinel_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_plan',
            field=models.ForeignKey(default=account.models.get_sentinel_plan, on_delete=models.SET(account.models.get_sentinel_plan), to='account.Plan'),
        ),
    ]
