# Generated by Django 2.2 on 2019-06-10 18:16

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190526_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.BinaryField(null=True, validators=[events.models.image_size_valid], verbose_name='img'),
        ),
    ]
