# Generated by Django 2.2 on 2019-05-26 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190526_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 7, 54, 2, 295928, tzinfo=utc), verbose_name='due'),
        ),
    ]
