# Generated by Django 2.2 on 2019-05-26 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190526_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='due',
            field=models.DateTimeField(default=datetime.timedelta(0), verbose_name='due'),
        ),
    ]
