# Generated by Django 2.2 on 2019-06-12 16:19

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190425_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.BinaryField(null=True, validators=[authentication.models.image_size_valid], verbose_name='img'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_connection_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last_connection_at'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='student_id'),
        ),
    ]
