# Generated by Django 2.2 on 2019-04-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='create_date',
        ),
    ]
